### ISSUE TITLE
Frame time?

### ISSUE THREAD

**Issue by antithing** [isarlab-department-engineering/SUPERSLAM3#1]
Hi, and thanks for making this code available!

What frame rate are you seeing with this code? 

Is stereo inertial mode at 50hz achievable?

Thanks!

**Comment by GiusMoll** [comment]
Hi antithing,

Thank you for your interest in our project.

The maximum frame rate of SUPERSLAM3 varies significantly depending on the specific hardware configuration. In our experience, the current implementation of SUPERSLAM3 generally runs slower than ORB-SLAM3 on equivalent hardware setups.

We've primarily focused on testing the configuration with a mono camera and have not yet incorporated inertial data. As a result, we haven't specifically measured the frame rate achievable with stereo inertial mode.
